version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    networks: 
      - elk-net
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elastic-data-vol
        target: /usr/share/elasticsearch/data
  kibana:
    image: kibana:7.5.1
    ports:
      - "5601:5601"
    networks: 
      - elk-net
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    depends_on:
        - elasticsearch

networks: 
  elk-net:
    driver: bridge

volumes:
  elastic-data-vol: